# Project Information
site_name: Awesome Devops

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/kimhan9
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/kimhan9

# Extensions
markdown_extensions:
  - abbr
  - footnotes
  - tables
